spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserver
    username: postgres
    password: 111
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone:  "http://localhost:8888/eureka"
    registerWithEureka: true
    fetchRegistry: true
  
